sudo: false
language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.2.6
- 2.3.3
- 2.4.2
- jruby-1.7.26
- jruby-9.1.9.0
gemfile:
- gemfiles/rails-3.0.gemfile
- gemfiles/rails-3.1.gemfile
- gemfiles/rails-3.2.gemfile
- gemfiles/rails-4.0.gemfile
- gemfiles/rails-4.1.gemfile
- gemfiles/rails-4.2.gemfile
- gemfiles/rails-5.0.gemfile
- gemfiles/rails-5.1.gemfile
- gemfiles/rails-edge.gemfile
env:
  global: RAILS_ENV=test
before_script:
- echo $BUNDLE_GEMFILE
- bundle install
script:
  - bundle exec rspec --format documentation
matrix:
  fast_finish: true
  exclude:
    - rvm: "1.9.3"
  include:
    - rvm: "1.9.3"
      gemfile: "gemfiles/rails-3.0.gemfile"
    - rvm: "1.9.3"
      gemfile: "gemfiles/rails-3.1.gemfile"
    - rvm: "1.9.3"
      gemfile: "gemfiles/rails-3.2.gemfile"
  allow_failures:
  - rvm: 1.9.3 # bundler wont install the gems
  - rvm: 2.4.2
    gemfile: gemfiles/rails-4.0.gemfile
  - rvm: 2.4.2
    gemfile: gemfiles/rails-4.1.gemfile
  - rvm: "jruby-1.7.26"
  - rvm: "jruby-9.1.9.0"
notifications:
  email: false
  slack:
    rooms:
      secure: F4BGVLUnaDqJ3YXfuIwx+m6047E8YstCUXs33Tfcs7SUlSuOSChuXqvCfVtnfNy2muF7xgB6VRL3xpFIRm7qNStqGUWCQJXmKq2OEgq1DYGkhAVle4d/LBtVcfBgeLelsoi+1TI9MrUtpZDHPl0li3PLoC+dq7rzSuhrxQ9EOhZlZGVn6LTeVcgNw6cLNzHSWJJ8zpYWLjBWUXgJ75MQvo5qaNbQxyfzm7GzEgRNfSzabFBwpKwB1Tog9X9TKTtPrn30O9Ur9+wmTu6EnwaDWZjaTK6I+AbxE8huIfUGvSrq1aV2JaDIra6zHEQ+d4j0oRYutgFM4YfyN9124MbPE2yH/5lXNQHMpUOsP0bl2U+KGDzq/V5APyrZ6irsvwGYpo3fSXrW8nDIAK4Mh8KB+Ta0zN5H8PmIRK76wJ+wG2zAtrfl+ailxMrdpK6J04fl3pCBuO6eW+AKEJ7Wfi5GiE7a9lk/YewAeDHyyLSnUNFIP0/iFAbTtRh5denCk0ZUS1XyfZNQuFoku7jk5lpe41SNItqOO0jv/jXPF+wensNa2UgMBIP0XkRw55LKn9eY0MKm9P+zp9ePaXs0T0Ttv4e0T4Jxrgf5QBynefgHwAsOI1nHr7GhlPaFQ6u8iNmjNYLB9v1JZMlO08LkytzZFpUuJoHbYYoBaRtUtEosBHg=
