sudo: false

language: ruby
cache: bundler

rvm:
  - 2.2
  - jruby

gemfile:
  - "gemfiles/rails-4.2.gemfile"

env:
  global: "RAILS_ENV=test"

before_script: "bundle install"

script: "bundle exec rspec"

matrix:
  fast_finish: true
  include:
    - rvm: "2.3.0"
      gemfile: "gemfiles/no_dependencies.gemfile"
      script: "bundle exec rubocop"
  exclude:
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "2.1.8"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "jruby-19mode"
      gemfile: "gemfiles/rails-5.0.gemfile"
  allow_failures:
    - rvm: "jruby-19mode"

env:
  global: "RAILS_ENV=test"

before_script: "bundle exec rake extension:install"

script: "bundle exec rake test"