sudo: false

language: ruby
cache: bundler

rvm:
  - 2.2
  - jruby

env:
  global:
    - RAILS_ENV=test
  matrix:
    - BUNDLE_GEMFILE=$PWD/gemfiles/rails-4.2.gemfile

matrix:
  fast_finish: true

before_script:
  - "bundle install"

script: "bundle exec rspec"
